set(CMAKE_IMAGE_SOURCE_FILE_EXTENSIONS uml dot)

set(CMAKE_IMAGE_COMPILE_OBJECT "<CMAKE_IMAGE_COMPILER> DEFINES <DEFINES> INCLUDES <INCLUDES> FLAGS <FLAGS> SOURCE <SOURCE> OUTPUT <OBJECT>")
set(CMAKE_IMAGE_OUTPUT_EXTENSION .svg)
